server:
  port: 8080


spring:
  application:
    name: GOSTERIM360
  datasource:
    url: jdbc:mysql://localhost:3306/gosterim360
    username: root
    password: 12345
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update


  mail:
    host: smtp.gmail.com
    port: 587
    username: orhantrkmn14@gmail.com
    password: rxofikviivohkkju

  messages:
    basename: messages
    encoding: UTF-8


springdoc:
  api-docs:
    version: openapi_3_0
    path: /swagger-ui.html

